add expo plugin
vonovak/react-native-add-calendar-event pull request #177
Opened 2023-05-15 11:42 UTC by mvanroon

This pull requests enables the installation of this library in a custom [Expo development build](https://docs.expo.dev/develop/development-builds/introduction/).

This way developers can use this package without having to eject their Expo app.

2023-05-15 11:47 UTC, vonovak commented on plugin/src/withAddCalendarEvent.ts
> +        if (!config.modResults.NSCalendarsUsageDescription) {
```suggestion
        if (!config.modResults.NSContactsUsageDescription) {
```

2023-05-15 11:48 UTC, vonovak requested changes
unexpected (not a very active project), but thank you! 😄

2023-05-15 11:48 UTC, mvanroon commented on plugin/src/withAddCalendarEvent.ts
> +        if (!config.modResults.NSCalendarsUsageDescription) {
woops - thanks!

2023-05-16 16:11 UTC, mvanroon commented
I've tested our fork in our app both Android and iOS are working as expected. Merge, release and publish when you're ready!

2023-05-16 20:08 UTC, vonovak commented on .gitignore
> -build/
why this change? the build artifacts should not be in git (the config plugin build included)

2023-05-17 06:37 UTC, mvanroon commented on plugin/build/withAddCalendarEvent.d.ts
I can remove it, but make sure you build the plugin before publishing to npm

2023-05-17 06:45 UTC, mvanroon commented on plugin/build/withAddCalendarEvent.d.ts
Also: most expo plugins also check in the build folder:

https://github.com/rnmapbox/maps/tree/main/plugin/build
https://github.com/expo/sentry-expo/tree/main/plugin/build
https://github.com/thebergamo/react-native-fbsdk-next/tree/master/plugin/build

2023-05-22 07:16 UTC, merged

2023-05-22 07:16 UTC, vonovak commented
thank you!

2023-05-22 16:25 UTC, mvanroon commented
@vonovak Thanks for merging and publishing. Could you also tag master?

2023-05-22 16:35 UTC, vonovak commented
@mvanroon published another with a clean commit and tag

2023-06-26 06:23 UTC, mvanroon commented
@vonovak seems like you published to npm without building the plugin first. Can you run `yarn build:plugin` and re-publish?

2023-06-26 06:36 UTC, vonovak commented
done :)

2023-06-26 06:39 UTC, vonovak commented
the plugin files would not be shipped even when included in the repo, they were ignored by npm :)

2023-06-26 06:43 UTC, mvanroon commented
Right! Thanks for the quick fix and publish!